# 应用基础配置
app:
  name: news-release-platform
  env: development  # 可选: development, testing, production
  port: 8080
  debug: false
  cors:
    allowed_origins:
      - "*" # 允许所有域名访问
      #- " "    # 允许访问后端API的前端域名
      #- "http://localhost:3000"  # 开发环境前端地址

# 数据库配置
database:
  driver: mysql
  host: ${NEWS_DB_HOST:-localhost}     # 从环境变量获取，默认 localhost
  port: ${NEWS_DB_PORT:-3306}          # 从环境变量获取，默认 3306
  username: ${NEWS_DB_USER:-root}      # 从环境变量获取，默认 root
  password: ${NEWS_DB_PASSWORD}        # 必须从环境变量获取
  dbname: ${NEWS_DB_NAME:-news_platform}     # 从环境变量获取，默认 news_platform
  max_open_connections: 100
  max_idle_connections: 20
  connection_max_lifetime: 300s